app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: 60
  base-url: http://localhost:8081
  admin:
    email: arnaud1720@gmail.com

spring:
  application:
    name: your_car_your_way
  # ============================================
  # CONFIGURATION EMAIL (Gmail)
  # ============================================
  # Pour Gmail, tu dois :
  # 1. Activer la validation en 2 étapes
  # 2. Créer un "mot de passe d'application" sur :
  #    https://myaccount.google.com/apppasswords
  # 3. Utiliser ce mot de passe ici
  # ============================================
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    url: jdbc:postgresql://localhost:5432/ycyw
    username: ${DB_USERNAME:ycyw_user}
    password: ${DB_PASSWORD:ycyw_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



# ============================================
# STRIPE
# ============================================
stripe:
  secret-key: ${STRIPE_API_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  frontend-url: http://localhost:4200

server:
  port: 8081

openai:
  api-key: ${OPENAI_API_KEY}
